<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBYZ9TA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBYZ9TA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXBYZ9TA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXBYZ9TA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXBYZ9TA\App_KernelDevDebugContainer([
    'container.build_hash' => 'XBYZ9TA',
    'container.build_id' => 'd8ff06c6',
    'container.build_time' => 1661441868,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBYZ9TA');
