index:
  path: /
  controller: App\Controller\DefaultController::index

circle:
  path: /circle/{radius}
  controller: App\Controller\CircleController::index
  methods: GET
  condition: "params[radius] > 0"

triangle:
  path: /triangle/{a}/{b}/{c}
  controller: App\Controller\TriangleController::index
  methods: GET
  condition: "params[a,b,c] > 0"