#index:
#    path: /
#    controller: App\Controller\DefaultController::index

circle:
  path: /circle/{r}
  controller: App\Controller\CircleController::index
  methods: GET
  condition: "params[r] > 0"

triangle:
  path: /triangle/{a}{b}{c}
  controller: App\Controller\TriangleController::index
  methods: GET
  condition: "context.getMethod() in ['GET'] and params[a,b,c] > 0"
